import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed-variant": "#394c2f",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "secondary-container": "#fe932c",
        "tertiary-fixed-dim": "#b7cda8",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#2f1500",
        "primary": "#003735",
        "glass-border": "rgba(255, 255, 255, 0.4)",
        "error-container": "#ffdad6",
        "on-primary-container": "#86bfbc",
        "moss": "#364531",
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#97d1ce",
        "primary-fixed": "#b3edea",
        "on-secondary": "#ffffff",
        "earth-clay": "#A36A4F",
        "tertiary-fixed": "#d3e9c3",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#404848",
        "inverse-primary": "#97d1ce",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0d4f4d",
        "primary-container": "#0d4f4d",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#3a4c2f",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00201f",
        "on-secondary-container": "#663500",
        "outline": "#707978",
        "tertiary": "#24351b",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#a6bc97",
        "on-secondary-fixed-variant": "#6e3900",
        "surface-container-low": "#f2f4f6",
        "glass-bg": "rgba(255, 255, 255, 0.7)",
        "on-tertiary-fixed": "#0f2008",
        "on-error": "#ffffff",
        "secondary": "#904d00",
        "outline-variant": "#bfc8c7",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "deep-teal": "#062E2D",
        "surface-tint": "#2d6765"
      },
    },
  },
  plugins: [],
};
export default config;
